- name: Fix Cordova Plugins Module
  run: |
    mkdir -p android/capacitor-cordova-android-plugins
    echo "ext {}" > android/capacitor-cordova-android-plugins/cordova.variables.gradle
    cat <<EOF > android/capacitor-cordova-android-plugins/build.gradle
    apply plugin: 'com.android.library'

    android {
        namespace "capacitor.cordova.plugins"
        compileSdk 34

        defaultConfig {
            minSdk 21
            targetSdk 34
        }
    }

    dependencies {
    }
    EOF
